name: "Bug Report"
description: "Report something that is broken or not working correctly"
title: "[Bug 🐞]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you’re encountering.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: Which version of the extension are you using?
